# Generated by Django 4.2.19 on 2025-03-11 15:35

from django.db import migrations, models
import django.db.models.deletion
import guide.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default=guide.models.generate_serial_number, max_length=50, unique=True, verbose_name='Серийный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип техники')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала гарантии')),
                ('end_date', models.DateField(verbose_name='Дата окончания гарантии')),
                ('terms', models.TextField(verbose_name='Условия гарантии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='guide.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('specs', models.JSONField(blank=True, null=True, verbose_name='Характеристики')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='guide.producttype', verbose_name='Тип техники')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='guide.productmodel', verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('in', 'Поступление на склад'), ('out', 'Отгрузка клиенту'), ('transfer', 'Перемещение между складами'), ('repair', 'Отправка в ремонт')], max_length=20, verbose_name='Тип перемещения')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='guide.product', verbose_name='Товар')),
            ],
        ),
    ]
