# Generated by Django 4.2.19 on 2025-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_product_description_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='specs',
        ),
        migrations.AlterField(
            model_name='movement',
            name='move_type',
            field=models.CharField(choices=[('in', 'Поступление на склад'), ('out', 'Поставлен в магазин'), ('repair', 'В ремонте')], max_length=20, verbose_name='Тип перемещения'),
        ),
    ]
