# Generated by Django 4.2.19 on 2025-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_remove_movement_notes_remove_productmodel_specs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='move_type',
            field=models.CharField(choices=[('in', 'Поступление на склад'), ('out', 'Поставлен в магазин'), ('repair', 'В ремонте'), ('in_use', 'В использовании')], max_length=20, verbose_name='Тип перемещения'),
        ),
    ]
