# Generated by Django 4.2.19 on 2025-05-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='processed_by',
        ),
    ]
