# Generated by Django 4.2.19 on 2025-05-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_remove_feedback_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Отвечено'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
