# Generated by Django 4.2.19 on 2025-05-12 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_feedback_is_replied_feedback_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_replied',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response',
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='Ответ')),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='guide.feedback')),
            ],
        ),
    ]
